version: '3.8'

services:
  # 1. The Database/Queue
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. The API
  api_service:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - redis_db
    environment:
      - REDIS_URL=${REDIS_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  # 3. The Worker
  worker_service:
    build: ./worker
    depends_on:
      - redis_db
    environment:
      - REDIS_URL=${REDIS_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}